#!/bin/sh

export LD_LIBRARY_PATH=/opt/anaconda3/lib

if [ -z "$NO_SERVICE" ] ; then

cargo run --bin service &

fi

if [ -z "$NO_UI" ] ; then

pushd ui
simple-http-server -p 8080 -i --nocache --try-file index.html &
cargo watch -s 'wasm-pack build --target web && rollup -c' &
popd

fi
