use core::GetWeightsQuery;
use std::ops::Deref;

use crate::services::RbpService;
use anyhow::Result;
use yew::{
  html, services::fetch::FetchTask, ChangeData, ComponentLink, Html, Properties, ShouldRender,
};
use yewtil::ptr::Mrc;

const DEFAULT_TICKERS: &[&str] = &["FB", "AAPL", "AMZN", "NFLX", "GOOG"];

pub enum Msg {
  WeightsResultsLoaded(Result<Vec<f64>>),
  TickersInputChanged(ChangeData),
}

#[derive(Properties, Clone, PartialEq)]
pub struct Props {
  pub rbp_service: Mrc<RbpService>,
}

pub struct Component {
  get_weights_task: Option<FetchTask>,
  link: ComponentLink<Self>,
  fetched_tickers: Vec<String>,
  picked_tickers: Vec<String>,
  fetched_weights: Vec<f64>,
  fetching_error: Option<()>,
  props: Props,
}

impl yew::Component for Component {
  type Message = Msg;
  type Properties = Props;

  fn create(props: Self::Properties, link: ComponentLink<Self>) -> Self {
    let default_tickers: Vec<String> = DEFAULT_TICKERS
      .iter()
      .map(Deref::deref)
      .map(str::to_string)
      .collect();
    let mut instance = Self {
      get_weights_task: None,
      link,
      props,
      picked_tickers: default_tickers.clone(),
      fetched_tickers: vec![],
      fetched_weights: vec![],
      fetching_error: None,
    };
    instance.get_weigths(GetWeightsQuery {
      tickers: default_tickers,
    });
    log::debug!("Weigths calculator component created");

    instance
  }

  fn update(&mut self, msg: Self::Message) -> ShouldRender {
    match msg {
      Msg::WeightsResultsLoaded(weights) => {
        self.get_weights_task = None;
        match weights {
          Ok(weights) => {
            self.fetching_error = None;
            self.fetched_tickers = self.picked_tickers.clone();
            self.fetched_weights = weights;
          }
          Err(_) => {
            self.fetching_error = Some(());
          }
        }
      }
      Msg::TickersInputChanged(change_data) => match change_data {
        ChangeData::Value(value) => {
          let tickers: Vec<String> = value
            .split(" ")
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .map(str::to_string)
            .collect();
          log::debug!("Changed tickers {:?}", &tickers);

          self.picked_tickers = tickers.clone();
          self.get_weigths(GetWeightsQuery { tickers })
        }
        _ => {}
      },
    }
    true
  }

  fn change(&mut self, _: Self::Properties) -> ShouldRender {
    log::debug!("Weigths calculator properties changed");
    false
  }

  fn view(&self) -> Html {
    html! {
      <>
      <div>
        <div>{"Pick you portfolio tickers"}</div>
        <input onchange=self.link.callback(Msg::TickersInputChanged) value={self.picked_tickers.join(" ")} />
      </div>
      <div>
        {self.build_weights_results()}
      </div>
      </>
    }
  }
}

struct TickerWeight {
  ticker: String,
  weight: f64,
}

impl Component {
  // TODO can this be generated by macro?
  fn get_weigths(&mut self, query: GetWeightsQuery) {
    log::debug!(
      "Getting weights for {}",
      serde_json::to_string(&query).unwrap()
    );
    if self.get_weights_task.is_some() {
      // TODO is this required to drop active task?
      self.get_weights_task.take();
    }
    self.get_weights_task = Some(
      self
        .props
        .rbp_service
        .as_ref()
        .get_weigths(query, self.link.callback(Msg::WeightsResultsLoaded)),
    );
  }

  fn build_weights_results(&self) -> Html {
    let render_ticker_weight = |(ticker, weight): (&String, &f64)| {
      html! {
        <div>
          <span>{ticker}</span>
          <span>{" = "}</span>
          <span>{weight}</span>
        </div>
      }
    };

    if self.get_weights_task.is_some() {
      html! {
        <div>{"Calculating weights..."}</div>
      }
    } else if self.fetching_error.is_some() {
      html! {
        <div>{"Sorry, failed to caculated weigts"}</div>
      }
    } else {
      html! {
      <>
        <div>{"Calculated porfolio weights"}</div>
        { for self.fetched_tickers.iter().zip(self.fetched_weights.iter()).map(render_ticker_weight) }
      </>
      }
    }
  }
}
