name: Pull request

defaults:
  run:
    shell: "bash --noprofile --rcfile build_fns -eo pipefail {0}"

on:
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: build_source
      - name: Build Service
        run: build_image service
      - name: Publish Service
        run: publish_image service
