name: Pull request

on:
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always
  BASH_ENV: build_fns

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Pre-Build
        run: |
          echo $PWD
          echo $0
          cat $0
          cp $0 /tmp/script
          cat /tmp/script
          echo $BUILDER_IMAGE
      - name: Build
        run: build_source
      - name: Build Service
        run: build_image service
      - name: Publish Service
        run: publish_image service
