name: Pull request

on:
  pull_request:
    branches: [master]

defaults:
  run:
    shell: bash

env:
  CARGO_TERM_COLOR: always
  BASH_ENV: build_fns

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: build_source
      - name: Build Service Image
        run: build_image service
      - name: Publish Service Image
        run: publish_image service
