name: Rust

defaults:
  run:
    shell: bash
    working-directory: scripts

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - run: source ./build_fns
      - name: Build
        run: build_image service
