name: Rust

defaults:
  run:
    shell: bash

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          source ./build_fns
          build_source
